config/routes.rb
Rails.application.routes.draw do
  root to: 'graficos#index'
  get 'graficos/new'
  post "graficos", to: "graficos#create"
  get "graficos/:id", to: "graficos#show", as: :grafico
  get 'graficos/home'
  get 'graficos/home2'
  get 'graficos/home3'
  get 'graficos/home4'
  get 'graficos/home5'
  get 'graficos/home6'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grafico.rb
class Grafico < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/graficos_controller.rb
class GraficosController < ApplicationController
  def index
    @graficos = Grafico.all
  end

  def show
    @grafico = Grafico.find(params[:id])
  end

  def new
    @grafico = Grafico.new # needed to instantiate the form_for
  end

  def create
    @grafico = Grafico.new(grafico_params)
    @grafico.save
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to grafico_path(@grafico)
  end

  private

  def grafico_params
    params.require(:grafico).permit(:sustainable, :self_organization, :technical_excellence, :planning_and_estimating,
      :effective_meetings, :size_and_skills, :allocation_and_stability, :workspace, :vision_and_purpose, :goals_and_outcomes,
      :quarterly_roadmap, :monthly_release, :weekly_iteration, :roles_and_expectations, :generalizing_specialities,
      :product_owner, :team, :stakeholder, :predictable_velocity, :time_to_market, :value_delivered,
      :quality, :response_to_change, :effective_facilitation, :leadership_1, :impediment_management,
      :leadership_2, :technical_expertise, :engagement, :backlog_management, :leadership_3,
      :leadership_4, :develop_people, :process_imp, :happiness, :collaboration, :trust_and_respect,
      :creativity_and_innovation, :accountability)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graficos_helper.rb
module GraficosHelper
end

app/views/graficos/home.html.erb
<h1>Hello World</h1>

app/views/graficos/home2.html.erb
<h1>Graficos Home 2</h1>

<div class="holder">
  <canvas id="myChart"></canvas>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script>
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
  type: 'radar',
  data: {
    labels: ["January;2015", "February;2015", "March;2015", "January;2016", "February;2016", "March;2016"],
    datasets: [{
      label: '# of Votes',
      xAxisID:'xAxis1',
      data: [12, 19, 3, 5, 2, 3]
    },
    {
      label: '# of Potatoes',
      xAxisID:'xAxis2',
      data: [9, 17, 28, 26, 29, 9],
      borderColor: '#0674ec'
    }]
  },
  options:{
    scales:{
      xAxes:[
        {
          id:'xAxis1',
          type:"category",
          ticks:{
            callback:function(label){
              var month = label.split(";")[0];
              var year = label.split(";")[1];
              return month;
            }
          }
        },
        {
          id:'xAxis2',
          type:"category",
          gridLines: {
            drawOnChartArea: false,
          },
          ticks:{
            callback:function(label){
              var month = label.split(";")[0];
              var year = label.split(";")[1];
              if(month === "February"){
                return year;
              }else{
                return "";
              }
            }
          }
        }],
      yAxes:[{
        ticks:{
          beginAtZero:true
        }
      }]
    }
  }
});
</script>

app/views/graficos/home3.html.erb
<script src="//www.amcharts.com/lib/4/core.js"></script>
<script src="//www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<div id="chartdiv" style="width: 100%; height: 1150px;"></div>

<script>
  // Themes begin
am4core.useTheme(am4themes_animated);
var colorSet = new am4core.ColorSet();
// Themes end
/* Create chart instance */
var chart = am4core.create("chartdiv", am4charts.RadarChart);
chart.innerRadius = am4core.percent(30);

/* Add data */
chart.data = [{
  "country": "Sustainable",
  "units": 8
}, {
  "country": "Self",
  "units": 6.5
}, {
  "country": "Technical",
  "units": 6.3
}, {
  "country": "Planning &",
  "units": 7.2
}, {
  "country": "Effective ",
  "units": 8.1
}, {
  "country": "Size & Skills",
  "units": 8.7
}, {
  "country": "Allocation &",
  "units": 8.5
}, {
  "country": "Workspace",
  "units": 7.6
}, {
  "country": "Vision &",
  "units": 8
}, {
  "country": "Goals &",
  "units": 8.5
}, {
  "country": "Quarterly/",
  "units": 2
}, {
  "country": "Monthly/",
  "units": 5.7
}, {
  "country": "Weekly/",
  "units": 5.3
}, {
  "country": "Roles &",
  "units": 7
}, {
  "country": "Generalizing",
  "units": 7.7
}, {
  "country": "Product",
  "units": 8
}, {
  "country": "Team",
  "units": 8.1
}, {
  "country": "Stakeholder",
  "units": 8.2
}, {
  "country": "Predictable",
  "units": 8.3
}, {
  "country": "Time",
  "units": 8.4
}, {
  "country": "Value",
  "units": 7.6
}, {
  "country": "Quality",
  "units": 7.5
}, {
  "country": "Response",
  "units": 7.7
}, {
  "country": "Effective",
  "units": 8.1
}, {
  "country": "Leadership1",
  "units": 7.2
}, {
  "country": "Impediment",
  "units": 7.2
}, {
  "country": "Leadership2",
  "units": 8.5
}, {
  "country": "Technical ",
  "units": 8.5
}, {
  "country": "Engagement",
  "units": 8.4
}, {
  "country": "Backlog Mgmt.",
  "units": 8.5
}, {
  "country": "Leadership3",
  "units": 6.5
}, {
  "country": "Leadership4",
  "units": 8.1
}, {
  "country": "Develop",
  "units": 7.5
}, {
  "country": "Process Imp.",
  "units": 7.4
}, {
  "country": "Happiness",
  "units": 4.0
}, {
  "country": "Colaboration",
  "units": 7.7
}, {
  "country": "Trust &",
  "units": 8
}, {
  "country": "Creativity &",
  "units": 6.5
}, {
  "country": "Accountability",
  "units": 6.5
}];

/* Create axes */
var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";
categoryAxis.renderer.labels.template.bent = true;
categoryAxis.renderer.labels.template.radius = -55;
categoryAxis.renderer.labels.template.location = 0.5;
categoryAxis.renderer.labels.template.fontSize = 9;
categoryAxis.renderer.labels.template.wrap = true;
categoryAxis.renderer.labels.template.maxWidth = 1;

categoryAxis.renderer.grid.template.strokeOpacity = 0.5;

var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.min = 0;
valueAxis.max = 13;
valueAxis.strictMinMax = true;
valueAxis.disabled = true;

var valueAxisRenderer = valueAxis.renderer;
valueAxisRenderer.axisFills.template.disabled = true;
valueAxisRenderer.ticks.template.disabled = true;
valueAxisRenderer.minGridDistance = 20;
valueAxisRenderer.grid.template.strokeOpacity = 0.05;

var series1 = chart.series.push(new am4charts.RadarColumnSeries());
series1.dataFields.valueY = "units";
series1.dataFields.categoryX = "country";
series1.name = "Units";
series1.strokeWidth = 0;
series1.columns.template.fill = am4core.color("#CDA2AB");

var labelBullet = series1.bullets.push(new am4charts.LabelBullet());
  labelBullet.label.text = "{valueY}";
  labelBullet.label.fill = am4core.color("black");
  labelBullet.locationY = 0.1;


function createRange(name, startCategory, finishCategory, rangeColor) {

  var range = categoryAxis.axisRanges.create();
  range.category = startCategory;
  range.endCategory = finishCategory;
  range.label.text = name;
  range.label.paddingBottom = 45;
  range.label.location = 0.5;
  range.label.fontWeight = "bolder";
  range.label.fontSize = 20;
  range.label.radius = -30;
  range.label.fill = am4core.color("#ffffff");
  range.label.bent = true;


  range.grid.disabled = false;
  range.grid.strokeWidth = 3;  

  var axisFill = range.axisFill;
  axisFill.innerRadius = -0.001; // almost the same as 100%, we set it in pixels as later we animate this property to some pixel value
  axisFill.radius = -45; // negative radius means it is calculated from max radius
  axisFill.disabled = false; // as regular fills are disabled, we need to enable this one
  axisFill.fillOpacity = 1;
  axisFill.togglable = true;
  axisFill.fill = am4core.color(rangeColor);
}

function createRange2(name, startCategory, finishCategory) {

  var range = categoryAxis.axisRanges.create();
  range.category = startCategory;
  range.endCategory = finishCategory;
  range.label.text = name;
  range.label.paddingBottom = 45;
  range.label.location = 0.5;
  range.label.fontWeight = "bolder";
  range.label.fontSize = 15;
  range.label.radius = -68;
  range.label.fill = am4core.color("black");
  range.label.bent = true;

  var axisFill = range.axisFill;
  axisFill.innerRadius = -37; // almost the same as 100%, we set it in pixels as later we animate this property to some pixel value
  axisFill.radius = -0.001; // negative radius means it is calculated from max radius
  axisFill.disabled = false; // as regular fills are disabled, we need to enable this one
  axisFill.fillOpacity = 1;
  axisFill.togglable = true;
  axisFill.fill = am4core.color("white");
  axisFill.stroke = am4core.color("black");
  axisFill.strokeWidth = 3;
}

function createRange3(name, startCategory, finishCategory) {

  var range = categoryAxis.axisRanges.create();
  range.category = startCategory;
  range.endCategory = finishCategory;
  range.label.text = name;
  range.label.paddingBottom = 45;
  range.label.location = 0.5;
  range.label.fontWeight = "bolder";
  range.label.fontSize = 12;
  range.label.radius = -380;
  range.label.fill = am4core.color("black");
  range.label.bent = true;
  range.stroke = am4core.color("red").lighten(-0.5);

  var axisFill = range.axisFill;
  axisFill.innerRadius = -350; // almost the same as 100%, we set it in pixels as later we animate this property to some pixel value
  axisFill.radius = 133; // negative radius means it is calculated from max radius
  axisFill.disabled = false; // as regular fills are disabled, we need to enable this one
  axisFill.fillOpacity = 1;
  axisFill.togglable = true;
  axisFill.fill = am4core.color("#ffffff");
  axisFill.stroke = am4core.color("black");
  axisFill.strokeWidth = 3;
}

function createRange4(name, startCategory, finishCategory) {

  var range = categoryAxis.axisRanges.create();
  range.category = startCategory;
  range.endCategory = finishCategory;
  range.label.text = name;
  range.label.paddingBottom = 45;
  range.label.location = 0.5;
  range.label.fontSize = 9;
  range.label.radius = -110;
  range.label.fill = am4core.color("black");
  range.label.bent = true;

  range.grid.disabled = true;


}

createRange("Clarity", "Vision &", "Generalizing", "#ffa64d");
createRange("Performance", "Product", "Response", "#267326");
createRange("Leadership", "Effective", "Process Imp.", "#4d4dff");
createRange("Culture", "Happiness", "Accountability", "#b30000");
createRange("Foundation", "Sustainable", "Workspace", "#0073e6");

createRange2("Vision", "Vision &", "Goals &")
createRange2("Planning", "Quarterly/", "Weekly/")
createRange2("Roles", "Roles &", "Generalizing")
createRange2("Confidence", "Product", "Stakeholder")
createRange2("Measurements", "Predictable", "Response")
createRange2("Team Facilitator", "Effective", "Impediment")
createRange2("Technical Leads", "Leadership2", "Technical ")
createRange2("Product", "Engagement", "Leadership3")
createRange2("Management", "Leadership4", "Process Imp.")
createRange2("Team Dynamics", "Happiness", "Accountability")
createRange2("Agility", "Sustainable", "Effective ")
createRange2("Team Structure", "Size & Skills", "Workspace")

createRange3("Clarity", "Vision &", "Generalizing");
createRange3("Performance", "Product", "Response");
createRange3("Leadership", "Effective", "Process Imp.");
createRange3("Culture", "Happiness", "Accountability");
createRange3("Foundation", "Sustainable", "Workspace");

createRange4("Innovation", "Creativity &", "Creativity &")
createRange4("Pace", "Sustainable", "Sustainable")
createRange4("Organization", "Self", "Self")
createRange4("Excellence", "Technical", "Technical")
createRange4("Estimating", "Planning &", "Planning &")
createRange4("Meetings", "Effective ", "Effective ")
createRange4("Stabililty", "Allocation &", "Allocation &")
createRange4("Purpose", "Vision &", "Vision &")
createRange4("Outcomes", "Goals &", "Goals &")
createRange4("Roadmap", "Quarterly/", "Quarterly/")
createRange4("Release", "Monthly/", "Monthly/")
createRange4("Iteration", "Weekly/", "Weekly/")
createRange4("Expectations", "Roles &", "Roles &")
createRange4("Specialists", "Generalizing", "Generalizing")
createRange4("Owner", "Product", "Product")
createRange4("Velocity", "Predictable", "Predictable")
createRange4("to Market", "Time", "Time")
createRange4("Delivered", "Value", "Value")
createRange4("to Change", "Response", "Response")
createRange4("Facilitation", "Effective", "Effective")
createRange4("Mgmt", "Impediment", "Impediment")
createRange4("Expertise", "Technical ", "Technical ")
createRange4("People", "Develop", "Develop")
createRange4("Respect", "Trust &", "Trust &")
</script>

app/views/graficos/home4.html.erb
<!-- Styles -->
<style>
#chartdiv {
  width: 100%;
  height: 500px;
}

</style>

<!-- Resources -->
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>

<!-- Chart code -->
<script>
am4core.ready(function() {

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

/* Create chart instance */
var chart = am4core.create("chartdiv", am4charts.RadarChart);

var data = [];
var value1 = 500;
var value2 = 600;

for(var i = 0; i < 12; i++){
  let date = new Date();
  date.setMonth(i, 1);
  value1 -= Math.round((Math.random() < 0.5 ? 1 : -1) * Math.random() * 50);
  value2 -= Math.round((Math.random() < 0.5 ? 1 : -1) * Math.random() * 50);
  data.push({date:date, value1:value1, value2:value2})
}

console.log(data)

chart.data = data;

/* Create axes */
var categoryAxis = chart.xAxes.push(new am4charts.DateAxis());

var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.extraMin = 0.2;
valueAxis.extraMax = 0.2;
valueAxis.tooltip.disabled = true;
valueAxis.labelRotation = "";

/* Create and configure series */
var series1 = chart.series.push(new am4charts.RadarSeries());
series1.dataFields.valueY = "value1";
series1.dataFields.dateX = "date";
series1.strokeWidth = 3;
series1.tooltipText = "{valueY}";
series1.name = "Series 2";
series1.bullets.create(am4charts.CircleBullet);
series1.dataItems.template.locations.dateX = 0.5;

var series2 = chart.series.push(new am4charts.RadarSeries());
series2.dataFields.valueY = "value2";
series2.dataFields.dateX = "date";
series2.strokeWidth = 3;
series2.tooltipText = "{valueY}";
series2.name = "Series 2";
series2.bullets.create(am4charts.CircleBullet);
series2.dataItems.template.locations.dateX = 0.5;

chart.scrollbarX = new am4core.Scrollbar();
chart.scrollbarY = new am4core.Scrollbar();

chart.cursor = new am4charts.RadarCursor();

chart.legend = new am4charts.Legend();
 

}); // end am4core.ready()
</script>

<!-- HTML -->
<div id="chartdiv"></div>

app/views/graficos/home5.html.erb
<script src="//www.amcharts.com/lib/4/core.js"></script>
<script src="//www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<div id="chartdiv" style="width: 100%; height: 1150px;"></div>

<script>
  // Themes begin
am4core.useTheme(am4themes_animated);
var colorSet = new am4core.ColorSet();
// Themes end
/* Create chart instance */
var chart = am4core.create("chartdiv", am4charts.RadarChart);
chart.innerRadius = am4core.percent(3);

/* Add data */
chart.data = [{
  "country": "Sustainable Pace",
  "units": 80
}, {
  "country": "Self Organization",
  "units": 65
}, {
  "country": "Technical Excellence",
  "units": 63
}, {
  "country": "Planning & Estimating",
  "units": 72
}, {
  "country": "Effective Meetings",
  "units": 81
}, {
  "country": "Size & Skills",
  "units": 87
}, {
  "country": "Allocation & Stabililty",
  "units": 85
}, {
  "country": "Workspace",
  "units": 76
}, {
  "country": "Vision & Purpose",
  "units": 80
}, {
  "country": "Goals & Outcomes",
  "units": 85
}, {
  "country": "Quarterly/Roadmap",
  "units": 20
}, {
  "country": "Monthly/Release",
  "units": 57
}, {
  "country": "Weekly/Iteration",
  "units": 53
}, {
  "country": "Roles & Expectations",
  "units": 70
}, {
  "country": "Generalizing Specialists",
  "units": 77
}, {
  "country": "Product Owner",
  "units": 80
}, {
  "country": "Team",
  "units": 81
}, {
  "country": "Stakeholder",
  "units": 82
}, {
  "country": "Predictable Velocity",
  "units": 83
}, {
  "country": "Time to Market",
  "units": 84
}, {
  "country": "Value Delivered",
  "units": 76
}, {
  "country": "Quality",
  "units": 75
}, {
  "country": "Response to Change",
  "units": 77
}, {
  "country": "Effective Facilitation",
  "units": 81
}, {
  "country": "Leadership1",
  "units": 72
}, {
  "country": "Impediment Mgmt",
  "units": 72
}, {
  "country": "Leadership2",
  "units": 85
}, {
  "country": "Technical Expertise",
  "units": 85
}, {
  "country": "Engagement",
  "units": 84
}, {
  "country": "Backlog Mgmt.",
  "units": 85
}, {
  "country": "Leadership3",
  "units": 65
}, {
  "country": "Leadership4",
  "units": 81
}, {
  "country": "Develop People",
  "units": 75
}, {
  "country": "Process Imp.",
  "units": 74
}, {
  "country": "Happiness",
  "units": 40
}, {
  "country": "Colaboration",
  "units": 77
}, {
  "country": "Trust & Respect",
  "units": 80
}, {
  "country": "Creativity & Innovation",
  "units": 65
}, {
  "country": "Accountability",
  "units": 65
}];

/* Create axes */
var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";
categoryAxis.renderer.labels.template.bent = true;
categoryAxis.renderer.labels.template.radius = -28;
categoryAxis.renderer.labels.template.location = 0.5;
categoryAxis.renderer.labels.template.fontSize = 7;

var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.min = 0;
valueAxis.max = 150;
valueAxis.tooltip.disabled = true;

var series2 = chart.series.push(new am4charts.RadarSeries());
series2.dataFields.valueY = "units";
series2.dataFields.categoryX = "country";
series2.name = "Units";
series2.strokeWidth = 3;
series2.stroke = am4core.color("black");
series2.dataItems.template.locations.categoryX = 0.5;


function createRange(name, startCategory, finishCategory, rangeColor) {

  var range = categoryAxis.axisRanges.create();
  range.category = startCategory;
  range.endCategory = finishCategory;
  range.label.text = name;
  range.label.paddingBottom = 45;
  range.label.location = 0.5;
  range.label.fontWeight = "bolder";
  range.label.fontSize = 20;
  range.label.radius = 14;
  range.label.fill = am4core.color("#ffffff");
  range.label.bent = true;

  range.grid.disabled = false;
  range.grid.strokeWidth = 3;
  range.grid.stroke = am4core.color("black");

  var axisFill = range.axisFill;
  axisFill.innerRadius = -0.001; // almost the same as 100%, we set it in pixels as later we animate this property to some pixel value
  axisFill.radius = -45; // negative radius means it is calculated from max radius
  axisFill.disabled = false; // as regular fills are disabled, we need to enable this one
  axisFill.fillOpacity = 1;
  axisFill.togglable = true;
  axisFill.fill = am4core.color(rangeColor);
}

function createRange2(name, startCategory, finishCategory) {

  var range = categoryAxis.axisRanges.create();
  range.category = startCategory;
  range.endCategory = finishCategory;
  range.label.text = name;
  range.label.paddingBottom = 45;
  range.label.location = 0.5;
  range.label.fontWeight = "bolder";
  range.label.fontSize = 15;
  range.label.radius = -34;
  range.label.fill = am4core.color("black");
  range.label.bent = true;
  range.grid.strokeWidth = 0;

  var axisFill = range.axisFill;
  axisFill.innerRadius = -37;
  axisFill.radius = -0.001; // negative radius means it is calculated from max radius
  axisFill.disabled = false; // as regular fills are disabled, we need to enable this one
  axisFill.fillOpacity = 1;
  axisFill.togglable = true;
  axisFill.fill = am4core.color("#ffffff");
  axisFill.stroke = am4core.color("black");
  axisFill.strokeWidth = 3;
}

function createRange3(startCategory, finishCategory) {

  var range = categoryAxis.axisRanges.create();
  range.category = startCategory;
  range.endCategory = finishCategory;

  var axisFill = range.axisFill;
  axisFill.innerRadius = 12;
  axisFill.radius = 1; // negative radius means it is calculated from max radius
  axisFill.disabled = false; // as regular fills are disabled, we need to enable this one
  axisFill.fillOpacity = 1;
  axisFill.togglable = true;
  axisFill.fill = am4core.color("black");
}

createRange("Clarity", "Vision & Purpose", "Generalizing Specialists", "#ffa64d");
createRange("Performance", "Product Owner", "Response to Change", "#267326");
createRange("Leadership", "Effective Facilitation", "Process Imp.", "#4d4dff");
createRange("Culture", "Happiness", "Accountability", "#b30000");
createRange("Foundation", "Sustainable Pace", "Workspace", "#0073e6");

createRange2("Vision", "Vision & Purpose", "Goals & Outcomes")
createRange2("Planning", "Quarterly/Roadmap", "Weekly/Iteration")
createRange2("Roles", "Roles & Expectations", "Generalizing Specialists")
createRange2("Confidence", "Product Owner", "Stakeholder")
createRange2("Measurements", "Predictable Velocity", "Response to Change")
createRange2("Team Facilitator", "Effective Facilitation", "Impediment Mgmt")
createRange2("Technical Lead(s)", "Leadership2", "Technical Expertise")
createRange2("Product Owner", "Engagement", "Leadership3")
createRange2("Management", "Leadership4", "Process Imp.")
createRange2("Team Dynamics", "Happiness", "Accountability")
createRange2("Agility", "Sustainable Pace", "Effective Meetings")
createRange2("Team Structure", "Size & Skills", "Workspace")

createRange3("Sustainable Pace", "Accountability")
</script>

app/views/graficos/index.html.erb
<div class="btn btn-primary">
  <%= link_to 'Create Grafico', graficos_new_path, :class => "btn"%>
</div>

  <% @graficos.each do |grafico| %>
    <li><%= grafico.sustainable %></li>
  <% end %>

app/views/graficos/new.html.erb
<%= form_for(@grafico) do |f| %>
  <%= f.label :sustainable %>
  <%= f.number_field :sustainable %>
  <%= f.label :self_organization %>
  <%= f.number_field :self_organization %>
  <%= f.label :technical_excellence %>
  <%= f.number_field :technical_excellence %>
  <%= f.label :planning_and_estimating %>
  <%= f.number_field :planning_and_estimating %>
  <%= f.label :effective_meetings %>
  <%= f.number_field :effective_meetings %>
  <%= f.label :size_and_skills %>
  <%= f.number_field :size_and_skills %>
  <%= f.label :allocation_and_stability %>
  <%= f.number_field :allocation_and_stability %>
  <%= f.label :workspace %>
  <%= f.number_field :workspace %>
  <%= f.label :vision_and_purpose %>
  <%= f.number_field :vision_and_purpose %>
  <%= f.label :goals_and_outcomes %>
  <%= f.number_field :goals_and_outcomes %>
  <%= f.label :quarterly_roadmap %>
  <%= f.number_field :quarterly_roadmap %>
  <%= f.label :monthly_release %>
  <%= f.number_field :monthly_release %>
  <%= f.label :weekly_iteration %>
  <%= f.number_field :weekly_iteration %>
  <%= f.label :roles_and_expectations %>
  <%= f.number_field :roles_and_expectations %>
  <%= f.label :generalizing_specialities %>
  <%= f.number_field :generalizing_specialities %>
  <%= f.label :product_owner %>
  <%= f.number_field :product_owner %>
  <%= f.label :team %>
  <%= f.number_field :team %>
  <%= f.label :stakeholder %>
  <%= f.number_field :stakeholder %>
  <%= f.label :predictable_velocity %>
  <%= f.number_field :predictable_velocity %>
  <%= f.label :time_to_market %>
  <%= f.number_field :time_to_market %>
  <%= f.label :value_delivered %>
  <%= f.number_field :value_delivered %>
  <%= f.label :quality %>
  <%= f.number_field :quality %>
  <%= f.label :response_to_change %>
  <%= f.number_field :response_to_change %>
  <%= f.label :effective_facilitation %>
  <%= f.number_field :effective_facilitation %>
  <%= f.label :leadership_1 %>
  <%= f.number_field :leadership_1 %>
  <%= f.label :impediment_management %>
  <%= f.number_field :impediment_management %>
  <%= f.label :leadership_2 %>
  <%= f.number_field :leadership_2 %>
  <%= f.label :technical_expertise %>
  <%= f.number_field :technical_expertise %>
  <%= f.label :engagement %>
  <%= f.number_field :engagement %>
  <%= f.label :backlog_management %>
  <%= f.number_field :backlog_management %>
  <%= f.label :leadership_3 %>
  <%= f.number_field :leadership_3 %>
  <%= f.label :leadership_4 %>
  <%= f.number_field :leadership_4 %>
  <%= f.label :develop_people %>
  <%= f.number_field :develop_people %>
  <%= f.label :process_imp %>
  <%= f.number_field :process_imp %>
  <%= f.label :happiness %>
  <%= f.number_field :happiness %>
  <%= f.label :collaboration %>
  <%= f.number_field :collaboration %>
  <%= f.label :trust_and_respect %>
  <%= f.number_field :trust_and_respect %>
  <%= f.label :creativity_and_innovation %>
  <%= f.number_field :creativity_and_innovation %>
  <%= f.label :accountability %>
  <%= f.number_field :accountability %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Graficos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body {
        font: 10px sans-serif;
      }

      .axis + .axis g text {
        display: none;
      }
      .chart {
        margin: auto;
        text-align:center;
      }
    </style>
    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="RadarChart.js" charset="utf-8"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>